// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/afthaab/task-manager/pkg/api"
	"github.com/afthaab/task-manager/pkg/api/handler"
	"github.com/afthaab/task-manager/pkg/db"
	"github.com/afthaab/task-manager/pkg/repository"
	"github.com/afthaab/task-manager/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi() (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectToDatabase()
	if err != nil {
		return nil, err
	}
	taskRepository := repository.NewTaskRepository(gormDB)
	taskUseCase := usecase.NewTaskUseCase(taskRepository)
	taskHanlder := handler.NewTaskHandler(taskUseCase)
	serverHTTP := api.NewServerHTTP(taskHanlder)
	return serverHTTP, nil
}
